# This is a basic workflow to help you get started with Actions
# https://downlodarchivelinux@dev.azure.com/downlodarchivelinux/dev-OS/_git/java11
name: GserverBuild

# Controls when the workflow will run
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
env:
  REPO_URL: https://downlodarchivelinux@dev.azure.com/downlodarchivelinux/Release/_git/Version
  REPO_BRANCH: master

jobs:
  build:
    name: Gserver
    runs-on: ubuntu-latest
    timeout-minutes: 559
    environment: production
    steps:
      - uses: actions/checkout@v1
      - name: Run delet script
        run: |
          git clone $REPO_URL
      - uses: ./Version
        with:
          MY_NAME: "Vserver"

      - name: Organize files
        id: organize
        run: |
          cd deployment
          #rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::encryptSrv_$(date +"3.0.%d%M"'.jar')"
          touch release.txt       
          echo "::set-output name=status::success"
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag}}
          body_path: release.txt
          files: ${{ env.FIRMWARE }}/*
 
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3   
